# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - appcontainer01

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5e16ec4dda9d43f9bb0e17540a7793aa }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f5e98c15b89040e2be4b7f60e26cc308 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5e16ec4dda9d43f9bb0e17540a7793aa }}/ubuntu:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'appcontainer01'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_97e15dcc69a84d678fc3385793327526 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5e16ec4dda9d43f9bb0e17540a7793aa }}/ubuntu:${{ github.sha }}'